### ISSUE TITLE
Conditions do not re-check their values over time

### ISSUE THREAD

**Issue by OmegaWulf** [Auxilor/EcoArmor#30]
**Describe the bug**
Conditions like `standing on block` only checks one time when the armor is put on. 

For example `standing on block` will only activate if you're standing on the block and put on the armor. If you walk off the target block and then back on, the effect will never fire again. 

**To Reproduce**
1. Add the following effect to an armor set:
```
      - id: add_stat
        args:
          stat: speed
          amount: 22
        conditions:
          - id: standing_on_block
            args:
              block: stone
```
2. Stand on stone and put on the armor. You will gain 22 speed.
3. Walk off the stone block and then walk back onto it. You never gain the 22 speed again.

**Expected behavior**
I expect the conditions to periodically check their values over time. This should probably be configurable for performance reasons. 

For example, an argument on a condition: `refresh` 

This argument takes either seconds or ticks and will re-check the condition over and over again. 

**Server Information (please complete the following information):**
- Latest Paper
- Latest Eco
